// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestingDurableFunction.Specflow
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TestingDurableFunctionFeature : object, Xunit.IClassFixture<TestingDurableFunctionFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "EmployeesMigration.feature"
#line hidden
        
        public TestingDurableFunctionFeature(TestingDurableFunctionFeature.FixtureData fixtureData, TestingDurableFunction_Specflow_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "TestingDurableFunction", "Testing the migration of employees from the legacy application to the new one", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Migrate employees")]
        [Xunit.TraitAttribute("FeatureTitle", "TestingDurableFunction")]
        [Xunit.TraitAttribute("Description", "Migrate employees")]
        public virtual void MigrateEmployees()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Migrate employees", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "First name",
                            "Last name",
                            "Email",
                            "Phone Number"});
                table1.AddRow(new string[] {
                            "1",
                            "Sofie",
                            "Blake",
                            "sofie.blake@test.com",
                            "+33612345678"});
                table1.AddRow(new string[] {
                            "2",
                            "Sion",
                            "Britton",
                            "sion.britton@test.com",
                            "+33687654321"});
                table1.AddRow(new string[] {
                            "3",
                            "Willie",
                            "Krueger",
                            "willie.krueger@test.com",
                            "+33654321678"});
#line 6
 testRunner.Given("These employees in the legacy application", ((string)(null)), table1, "Given ");
#line hidden
#line 11
 testRunner.When("The migration process is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "First name",
                            "Last name",
                            "Email",
                            "Phone Number",
                            "Full name"});
                table2.AddRow(new string[] {
                            "1",
                            "Sofie",
                            "Blake",
                            "sofie.blake@test.com",
                            "+33612345678",
                            "Sofie Blake"});
                table2.AddRow(new string[] {
                            "2",
                            "Sion",
                            "Britton",
                            "sion.britton@test.com",
                            "+33687654321",
                            "Sion Britton"});
                table2.AddRow(new string[] {
                            "3",
                            "Willie",
                            "Krueger",
                            "willie.krueger@test.com",
                            "+33654321678",
                            "Willie Krueger"});
#line 12
 testRunner.Then("These employees are saved into the new application", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TestingDurableFunctionFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TestingDurableFunctionFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
